import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './layouts/navbar/Navbar'

const workSans = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Maeva Ianja Estelle portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={` bg-blue text-white ${workSans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
