import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './layouts/navbar/Navbar'
import { useLocale } from 'next-intl'
import { notFound } from 'next/navigation'

const workSans = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Maeva Ianja Estelle portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const locale = useLocale()
  if (params.locale !== locale) {
    notFound()
  }
  return (
    <html lang={locale}>
      <body className={` bg-blue text-white ${workSans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
